version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1
      - DB_HOST=db
      - DB_NAME=yii2_admin
      - DB_USER=yii2user
      - DB_PASS=yii2password

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=yii2_admin
      - MYSQL_USER=yii2user
      - MYSQL_PASSWORD=yii2password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 